# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0608c85a-13b4-4f22-a5ce-4d18f3b4be4b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0608c85a-13b4-4f22-a5ce-4d18f3b4be4b".device = "/dev/disk/by-uuid/0608c85a-13b4-4f22-a5ce-4d18f3b4be4b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B8D9-CDEB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
